equinix/ansible-collection-equinix

.github/workflows/integration-tests.yml

This is to test if we need the aws collection for anything.

Remove aws collection dependency from integration test Github action

---

.github/workflows/release.yml

This PR adds a workflow for releases. 
This still needs:
- @displague please log in to https://galaxy.ansible.com/accounts/login/ with Equinix creadentials and create collection `equinix.cloud`
- acquire GALAXY_TOKEN that can add releases to the `equinix.cloud` collection
- Add GALAXY_TOKEN to the METAL_API_TOKEN Gtihub Actions env (and maybe consider renaming the METAL_API_TOKEN env)
Anyway, this is one of the things that we won't know if it works until we try.

Add Github Action for Ansible Galaxy release

---

plugins/module_utils/equinix.py

This PR removes requirements info from module docs. It's hard to point to the current version in Makefile, and it doesn't really matter per module, and in module docs.

remove requirements from module docs

---

plugins/modules/metal_available_ips_info.py
plugins/modules/metal_device.py
plugins/modules/metal_device_info.py
plugins/modules/metal_ip_assignment.py
plugins/modules/metal_ip_assignment_info.py
plugins/modules/metal_project.py
plugins/modules/metal_project_info.py
plugins/modules/metal_reserved_ip_block.py
plugins/modules/metal_reserved_ip_block_info.py

This PR follows #91 and removes the requirements block from the module doc markdown.

Remove "requirements" block from module doc markdown

---

requirements.txt

Equinix_metal library expects pydantic version less than two, as it's using a deprecated object type. Until this is fixed in equinix_metal, we need to set pydantic to a version bellow 2 to prevent deprecation errors.

set pydantic to specific version (1.10.2), to prevent deprication errors

---

.github/workflows/integration-tests-pr.yml
.github/workflows/integration-tests.yml

This PR adds workflow to run integration tests for a PR. It doens't run the tests automatically but it's triggered manually, from Actions section of the repo, and it's got params test, hash, PR num.
I think only people with write access to the repo can trigger the test. I'm not sure if this is a good thing as Equinix Metal integration tests can flaky, as we know from the TF provider. 
It's taken from Linode ansible collection.

Add manual trigger for integration test workflow for PRs

---

.gitignore

When we run tests locally, `tests/integration/integration_config.yml` gets modified (path to python executable I think), and the file gets dirty. We then have to pay attention not to add it to the index and accidentally commit it.
Let's see if the tests run when `tests/integration/integration_config.yml` is in gitignore.

ignore integration_config.yml for smoother development flow

---

README.md

This https://galaxy.ansible.com/equinix/cloud/ URL is currently 404'ing. This may be a temporary problem.
https://forum.ansible.com/t/403-for-galaxy-api-when-publishing-collection-to-galaxy-ansible-com/1445

docs: Update Galaxy published module URL

---

README.md
template/README.template.md

This PR 
- fixes main README so that it points to dev doc DEVELOPMENT.md instead of explaining collection development in place.
- fixes link for collection release

fixes in readme

---

DEVELOPMENT.md

This PR adds devenv info to dev doc. It suggests Python 3.8 for development.

docs: Add devenv setup info to DEVELOPMENT.md, specify Python3.8

---

plugins/module_utils/metal/metal_client.py

fixes #128 
I tested it and now the user agent is `[user_prefix ] ansible-equinix metal-python/0.3.0`

fix: preserve SDK user agent in collection client

---

README.md

Simple typo - .MD to MIGRATION.md

docs: fix link to MIGRATION.md

---

DEVELOPMENT.md

This 
- adds debugging info to the dev doc. (sectoin 1.1)
- fixes var name for listing keys
https://github.com/equinix-labs/ansible-collection-equinix/blob/metion_q_in_dev_guide/DEVELOPMENT.md

docs: development docs improvements

---

plugins/module_utils/metal/api_routes.py
requirements.txt

This PR bumps equinix_metal to v0.5.0, it
- introduces all-page listers (from v0.4.0)
- fixes Plans api class to unblock #146

feat: bump equinix_metal to v0.5.0, update listing methods

---

requirements.txt

chore: bump equinix-metal to v0.6.0

---

.github/workflows/integration-tests-pr.yml
.github/workflows/integration-tests.yml

This PR bumps Python version used in integration tests to 3.10. We might need it if we want to use GHA to publish collection to Galaxy.
Related to #154

feat: use Python 3.10 in integration tests

---

.github/workflows/validate_pr.yml

This PR adds GHA checking titles of PRs to be in semantic commit format. We've got similar GHAs in other EM DevRel projects.

ci: add GHA for validating PR titles to be in semantic commit format

---

.github/workflows/release.yml
.releaserc.json
template/README.template.md

This PR fixes doc links in readme and plugs doc generation just before GitHub release, so that we have properly-versioned links in main README. Now the doc for metal_device in main-branch README will point to 
https://github.com/equinix-labs/ansible-collection-equinix/blob/v0.3.0/docs/modules/metal_device.md
(when v0.3.0 is the latest release)

ci: Fix docs generation in releasing GitHub action

---

.github/workflows/release.yml

This PR fixes working directory for Ansible commands in the release GHA
It should fix fail of the release action:
https://github.com/equinix-labs/ansible-collection-equinix/actions/runs/8015714250/job/21896329577#step:6:12

ci: fix path for GHA blocks

---

.github/workflows/integration-tests-pr.yml
.github/workflows/integration-tests.yml

This PR adds secret ANSIBLE_ACC_METAL_DEDICATED_CONNECTION_ID to integration test pr as an env var so that we can use it in #141

ci: add ANSIBLE_ACC_METAL_DEDICATED_CONNECTION_ID to test GHA

---

plugins/modules/metal_connection.py
requirements.txt

This PR bumps mp to 0.8.0 and pydantic to 2>= 2
I had to fix metal_connection module so that it's passing string (not int) as `speed` to the SDK.

chore: bump metal-python to 0.9.0 and pydantic to >= 2

---

.github/workflows/docs-generation-test-pr.yml

This PR adds GHA that will run `make docs`. If that succeeds, it's guaranteed that docs are properly generated and that the format is OK for ansible-doc, which should render well in ansible-galaxy.
It's triggered in PRs or manually, auth token not needed so also no authorization.
I think we need to merge this to test properly.

ci: add pr-triggered GHA to validate ansible-specdoc documentation

---

README.md
template/README.template.md

This PR fixes link to dynamic inventory docs in README

docs: fix link to dynamic inventory docs in README

---

docs/modules/metal_device_info.md
plugins/modules/metal_device_info.py

Found references in the docs pertaining to device_info that were using the old module and thus didn't work, so updating the references to point to the current module.

docs: fix device info docs to point at equinix.cloud

---

plugins/module_utils/equinix.py

When using reserved hardware the api https://github.com/equinix-labs/ansible-collection-equinix/blob/55bc3d1b645a859b7b3c93309cf5b264d23a4976/plugins/modules/metal_device.py#L373 says you can provide `next-available` instead of the device uuid, but currently this is still checked against the uuid  regex and the exception is thrown https://github.com/equinix-labs/ansible-collection-equinix/blob/55bc3d1b645a859b7b3c93309cf5b264d23a4976/plugins/module_utils/equinix.py#L110 
Skipping the uuid check if this is the case.

fix: skip uuid check when hardware_reservation_id is next-available

---

requirements.txt

fix: upgrade metal-python to remove validation errors for Metal plans

---

docs/modules/metal_vlan.md
plugins/module_utils/equinix.py
plugins/module_utils/metal/metal_api.py
plugins/modules/metal_vlan.py
tests/integration/targets/metal_vlan/tasks/main.yml

right now, passing the vxlan id is mandatory if one wants to create a new metal_vlan. with this patch, we allow omitting the vxlan id (while passing a set of tags), and metal api picks one available id for us. useful when we don't want to worry about managing ids. if the same call with the same tags are passed, the module should find the resource that was previously created with the same set of tags.
reference: https://developer.equinix.com/catalog/metalv1#operation/createVirtualNetwork

feat: metal_vlan to allow metal api to automatically pick vlan id

---

plugins/module_utils/metal/metal_api.py

vlans can be facility based, but the current metal_vlan_info code doesn't handle that case - it fails since a facility based vlan doesn't have the metro field, which is treated as required by the VLAN_RESPONSE_ATTRIBUTE_MAP.
this PR changes the metro attribute to be optional, and adds a new optional attribute for the facility, so it can handle both cases
```
{
"description": "native vlan",
"facility": { <<<
"href": "/metal/v1/facilities/d2a72094-26c9-4372-8d65-051424bc370a",
"id": "d2a72094-26c9-4372-8d65-051424bc370a"
},
"id": "abcd",
"metro": "",
"vxlan": 1004
},
{
"description": "Public NAT",
"facility": "",
"id": "abcd",
"metro": { <<<
"href": "/metal/v1/locations/metros/d3d6b29f-042d-43b7-b3ce-0bf53d5754ca",
"id": "d3d6b29f-042d-43b7-b3ce-0bf53d5754ca"
},
"vxlan": 1004
},
``` …

feat: metal_vlan_info supports facility based vlans

---

plugins/module_utils/metal/metal_api.py
tests/integration/targets/metal_gateway/tasks/main.yml

it might be useful to know the metal gateways on a vlan, so it makes sense to expose it in this module

feat: metal_vlan to return metal_gateway field from api response

---

plugins/module_utils/metal/metal_api.py
plugins/modules/metal_device.py
tests/integration/targets/metal_device/tasks/main.yml

when we create a device, the api returns the network_ports for that device - but the ansible module doesn't expose any of that.
this PR adds the network_ports attribute to the response in the ansible task, containing a minimum amount of attributes about the port configuration (id, name, bond, vlans, network_type).

feat: metal_device return network ports from api response

---

CONTRIBUTING.md
DEVELOPMENT.md
MIGRATION.md
README.md
examples/device_assign_ip/README.md
template/README.template.md
template/galaxy.template.yml

This updates docs to link to this repo under github.com/equinix instead of github.com/equinix-labs.  This is being contributed with the `feat:` tag so that we can cut a release after moving the repo, which will propagate the following things to Ansible Galaxy:
- These docs updates
- The recent switch from `metal-python` to `equinix-sdk-python`

feat: update docs to reference new repo location

---

plugins/modules/metal_device.py

Fixes #224 
A device that is not privisionable will fail when we try to provision on it. Thus, removing the extra check of validation if a device is provisionable or not allows us to pass `next-available` as the h/w reservation id.

fix: Update code to allow `next-available` for h/w reservation id in metal_device module

---

examples/device_network_types/README.md
examples/device_network_types/main.yml
examples/device_network_types/vars/equinix_metal_vars.yml

The generated Ansible collection docs don't give us much leeway to describe example task configurations in detail.
The goal of this PR is to add a separate, hand-written Markdown example that provides more detail as to the purpose/effect of different combinations of arguments for the `metal_port` module.
The example includes a playbook that largely duplicates the existing integration tests for the `metal_port` module, with a `README.md` alongside the playbook that describes the functionality of each task, analogous to the [network types guide for the Terraform provider](https://registry.terraform.io/providers/equinix/equinix/latest/docs/guides/network_types).

docs: more descriptive markdown example for metal_port

---

docs/modules/metal_reserved_ip_block.md
plugins/modules/metal_reserved_ip_block.py

This fixes a couple problems with the parameter definitions for the reserved IP block module:
1. The `cidr` and `network` parameters, needed for VRF IP reservations, were not defined in the module spec
2. The `quantity` parameter, which is unsupported for VRF IP reservations, was required in order to create _any_ IP reservation
This PR updates the reserved IP block module so that it can be used to create a VRF IP reservation.  The docs are also updated to reference the `cidr` and `network` parameters.
This was broken out of #232.

fix: enable `metal_reserved_ip_block` to create VRF IP reservations

---

docs/modules/metal_virtual_circuit.md
plugins/module_utils/equinix.py
plugins/module_utils/metal/metal_api.py
plugins/modules/metal_virtual_circuit.py

Fixes #237
This marks additional attributes as `mutable` in the virtual circuit module specs.  In addition to marking the attributes as `mutable`, we also need to add a flag to the shared `get_diff` function to tell that function _not_ to ignore fields that are not present in the API response but are present in the config.
This also registers the `md5` attribute as a response attribute for virtual circuits so that the module will know about that attribute and handle it correctly.

fix: support updating virtual circuit attributes other than name

---

plugins/modules/metal_reserved_ip_block.py

This uses the `network` attribute, if it is specified in the task config, to differentiate between different IP reservations of the same type in the same metro.
Fixes #235

fix: support multiple reserved IP blocks of same type in a metro

---

.releaserc.json

The release workflow occasionally fails due to GitHub API rate limiting on the success comments that are posted to every issue and PR that is included in the release.  While it's possible this problem has been addressed in the latest version of `semantic-release/github`, I still think it's better to disable those comments and avoid the problem entirely.

chore(ci): disable release comments to avoid secondary rate limit

---

plugins/module_utils/metal/metal_api.py

This updates the API response mapper for Metal connections so that Ansible collection users can access `service_tokens` for a Metal connection without having to go to the [Equinix Metal console](https://console.equinix.com).

feat:  expose service tokens for Metal connections
